name: Release

on:
  push:
    branches:
      - main
      - master
      - next
      - next-major
      - beta
      - alpha
      - '[0-9]+.[0-9]+.x'
      - '[0-9]+.x'

env:
  node-js-version: 20.x
  author-name: Marc Scheib
  author-email: marc.scheib@cycrilabs.com

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout [${{ github.head_ref || github.ref_name }}]
        uses: actions/checkout@v4

      - name: Setup Node.js [${{ env.node-js-version }}]
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.node-js-version }}

      - name: Install Dependencies
        run: npm i --prefer-offline --no-audit --force

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_NAME: ${{ env.author-name }}
          GIT_AUTHOR_EMAIL: ${{ env.author-email }}
        run: npx semantic-release

  tag:
    name: Add additional tags
    runs-on: ubuntu-latest
    needs: release
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}
          fetch-depth: 0 # required to get all history for git describe

      - name: Retrieve last tag
        run: |
          echo "TAG_MAJOR_MINOR=$(git describe --abbrev=0 --tags | cut -d. -f1,2)" >> $GITHUB_OUTPUT
          echo "TAG_MAJOR=$(git describe --abbrev=0 --tags | cut -d. -f1)" >> $GITHUB_OUTPUT
        id: version

      - name: Add additional tags
        run: |
          git config --global user.name '${{ env.author-name }}'
          git config --global user.email '${{ env.author-email }}'
          git tag --force ${{ steps.version.outputs.TAG_MAJOR_MINOR }}
          git tag --force ${{ steps.version.outputs.TAG_MAJOR }}
          git push --tags --force
